### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by GraphiteGraphic** [mdoleh/MoodMonsters#2]
Scenario 1:
- When the wrong answer is selected. On return to the first scenario first question, the crossed out X's appear over the second and third option.

**Comment by mdoleh** [comment]
Scenario 1:
- When the wrong answer is selected. On return to the first scenario first question, the crossed out X's appear over the second and third option. **Fixed, forgot to replace the images**
- Ty's head clips into the scene on occasion when the camera shifts to Lily's face **Moved camera closer to Lily's face**

Scenario 2
- Was asked for gender of adult, even when clicked adult wasn't there - **Do you mean you selected the Scared Scene then you answered no adult present and it asked you the gender anyway?**
- The camera shifts away from the scared kid, so I can't see any animations during the body questions (couldn't repeat) **Fixed, needed to reset the original values for the camera so it updates properly**
- Was stuck on a loading screen after answering "Throw a Tantram" or "Run Away" **SceneReset was configured incorrectly**

Scenario 3
- No bugs found

Scenario 4
- Got locked in a scene without being able to quit out when answer "Brag" or "Complain" **CanvasList in ActionsMenu scene wasn't configured properly**

General Bugs
- The camera won't properly change on occasion to the proper angle (seemingly random) - **I think this is fixed now, a different issue (#7) showed it was due to the original camera position not saving properly**
- If the wrong answer is given when the camera is in the wrong position, it freezing on the loading screen. - **With above issue fixed, this one is no longer relevant**

**Comment by mdoleh** [comment]
@damha122 You need to split this issue into separate issues for each bug.

**Comment by mdoleh** [comment]
This has been broken into separate issues. Closing.
